services:
  - type: web
    name: kanban-board
    env: node
    buildCommand: node render-build.js
    startCommand: cd server && node dist/server.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-db
          property: connectionString

databases:
  - name: kanban-db
    databaseName: kanban_db
    plan: free