services:
  - type: web
    name: kanban-board
    env: node
    buildCommand: node render-build.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true